spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: a123456789
    username: root
    url: jdbc:mysql://localhost:3306/go?useSSL=false&useUnicode=true&characterEncoding=utf-8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl